### ISSUE TITLE
game crashes on start

### ISSUE THREAD

**Issue by Hurokun** [Ferlern/extended-UI#1]
game crashes with an error message on start. 
mods installed are UI Lib and Extended UI.
crash report:

```
Mindustry has crashed. How unfortunate.
Version: pre-alpha build 135
OS: Windows 10 x64 (amd64)
Java Version: 17.0.1
Mods: extended-ui:0.16, ui-lib:2.16.6

rhino.EcmaError: TypeError: Cannot call method "row" of null (power-ui#40)
	at rhino.ScriptRuntime.constructError(ScriptRuntime.java:3741)
	at rhino.ScriptRuntime.constructError(ScriptRuntime.java:3721)
	at rhino.ScriptRuntime.typeError(ScriptRuntime.java:3750)
	at rhino.ScriptRuntime.typeError2(ScriptRuntime.java:3766)
	at rhino.ScriptRuntime.undefCallError(ScriptRuntime.java:3780)
	at rhino.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2181)
	at rhino.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2175)
	at rhino.optimizer.OptRuntime.callProp0(OptRuntime.java:69)
	at rhino.gen.power_ui_8._c_anonymous_3(power-ui:40)
	at rhino.gen.power_ui_8.call(power-ui)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:328)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3114)
	at rhino.gen.power_ui_8.call(power-ui)
	at rhino.ArrowFunction.call(ArrowFunction.java:33)
	at rhino.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:141)
	at rhino.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:92)
	at rhino.Context.call(Context.java:450)
	at rhino.ContextFactory.call(ContextFactory.java:428)
	at rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:92)
	at rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:142)
	at jdk.proxy1/jdk.proxy1.$Proxy1.get(Unknown Source)
	at mindustry.ClientLauncher.lambda$update$11(ClientLauncher.java:159)
	at arc.Events.lambda$fireWrap$3(Events.java:37)
	at arc.struct.Seq.each(Seq.java:199)
	at arc.Events.fireWrap(Events.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:157)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:166)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:154)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
```

**Comment by Ferlern** [comment]
v6 and v7 have different huds, and i don't know how do deal with it rn.
Temporarily fixed this issue by moving power bar to another location (only for v7).

Now mod should work.

![image](https://cdn.discordapp.com/attachments/606977691757051920/950816998269538364/unknown.png)
